### ISSUE TITLE
Play button does not work when user does not interact with browser before music starts playing

### ISSUE THREAD

**Issue by ManasMahanand** [freeCodeCamp/coderadio-client#81]
![image](https://user-images.githubusercontent.com/41644157/86116388-fbedca00-baea-11ea-9f27-9fea777e29af.png)

What this means is that for a user who opens the app, the music will not be audible even if it shows as playing. And when user clicks on pause and play again, the music still isn't audible.

The only thing the user can do is to immediately click on the page when the app is loading or before the music starts to play, which is not intuitive at all.

Maybe you can keep the audio paused by default and prompt user to click play, instead of trying to play it automatically.

**Comment by ManasMahanand** [comment]
If this is a worthy issue to solve, I would like to make the changes my self. I just want to know if there are any guidelines freecodecamp sets to follow?

**Comment by ahmadabdolsaheb** [comment]
I could not replicate this issue. However I see that we are trying to play the music on component did mount with getNowPlaying. 
https://github.com/freeCodeCamp/coderadio-client/blob/0d6335ba62b41d7abceb2e187e5714f2bf960f02/src/components/App.js#L93

Playing the music should probably await user interaction. 

I believe we experienced a similar issue before.

Any preference on how we should proceed, @huyenltnguyen?

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb The `getNowPlaying` is just to receive data from websocket. We play the music by listening to the hotkey press and the button click events, so unless the user interacts with the page, the music should not start. Having this error in the first place is kind of strange.

I have a feeling that this has to do with the error handling function, as I'm seeing the certificate error in OP's console. My theory is:
- OP lands on the page
- The first stream URL they got had certificate issue (https://github.com/freeCodeCamp/coderadio-client/issues/79)
- The page switches to a new stream and tries to play it
- Since OP didn't interact with the page, the browser blocks the audio from playing

Now that the certificate issue has been resolved, I believe the page should be working as expected. But I'll investigate and raise a PR asap to fix this issue.

@ManasMahanand Thanks a lot for bringing this up to our attention, and sorry about the inconvenience.

**Comment by ahmadabdolsaheb** [comment]
Thanks, for the explanation, @huyenltnguyen. 
@ManasMahanand, could you double check if the issue still persists?

**Comment by ManasMahanand** [comment]
This issue has been solved as far as I can see.

This is what is seen when the browser loads now:
![image](https://user-images.githubusercontent.com/41644157/86615374-00761f00-bfd2-11ea-9193-f79fa417f651.png)


So user has to press play to start music:
![image](https://user-images.githubusercontent.com/41644157/86615321-ef2d1280-bfd1-11ea-8616-ab8f0c5dbc7c.png)

This issue does not seem to persist.
